---
title: "EDA_presentation"
author: "Amaya Jerdee"
date: "4/5/2021"
output: github_document
---

## Abstract

Covid-19, also known as a newly discovered Coronavirus, is an infectious disease that is expressed through moderate respiratory illness spreading by droplets of saliva or discharge from the nose. Individuals with a higher risk to contracting Covid-19 include people with pre-existing conditions such as, cardiovascular disease, diabetes, chronic respiratory disease, and cancer, but not limited to just this group. I am curious to know the population to death ratio of the different races and ethnicities due to Covid-19. The data set that will be used to explore this question is "The Covid Tracking Project" from The Atlantic. I will compare the population of each ethnicity per state with the amount of deaths in each population using exploratory data analysis.

## Introduction

## Methods

variables, describe variables,

### Data Acquisition

The data was obtained from The Covid Tracking Project at <https://covidtracking.com/race/dashboard> ("Racial Data Dashboard." 2021). To obtain spreadsheet, click CSV link in the third paragraph of the top section of the page to download the data. After obtaining the data, I used the read_csv function from the tidyverse package (R Core Team 2019) to upload the data into Rstudio.

That sampling unit of this data is a date and a state. Measured variables include cases, deaths, hospitalizations, and tests. For each of these variables there are 13 columns, each representing a different race or ethnicity.

### Data Preparation

For the data analysis, I used Rstudio version 1.3.1093 (R Core Team 2020) and R version 4.0.3 (R Core Team 2020) for wrangling and data analysis. The data obtained was displayed in table1 which displayed the summary of data collected from all the states. I then used the summarize function from the tidyverse package (R Core Team 2019) to group by state, recorded number of cases, and recorded number of deaths.

## Results

## Discussion

## Literature Cited

1.  "Racial Data Dashboard." The COVID Tracking Project, The Atlantic, 2021, covidtracking.com/race/dashboard.

2.  R Core Team (2020). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL <https://www.R-project.org/>.
